title = "Adam Binks"
baseURL = "https://adambinks.me"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "G-K15E0YCM0F"  # add your tracking id

[params]
  author = "Adam Binks"
  description = "PhD student at the University of St Andrews."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = ":)"
    url = "#"

[permalinks]
  "/" = "/:filename"

[menu]
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/adam-binks"
        weight = 1
    [[menu.main]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/adam-binks/"
        weight = 1
  # [[menu.main]]
  #   name = "CV"
  #   url = "/CV.pdf"
  #   # 'pre' and 'post' hooks are available
  #   # here we use an icon from Bootstrap https://icons.getbootstrap.com/
  #   weight = 2
  # [[menu.main]]
  #   name = "Contact"
  #   url = "/contact"
  #   weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
